name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '21.3.0'
        java-version: '17'
        components: 'native-image'
    - name: Build with Maven Wrapper
      run: ./mvnw -B package
