name: Maven native image build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [17, 21]
        graalvm-distribution: ['graalvm-community']
      fail-fast: false

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Set up GraalVM ${{ matrix.graalvm-distribution }} for Java ${{ matrix.java-version }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.graalvm-distribution }}

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Build with Maven Wrapper (Linux)
        run: ./mvnw -V -B package
        if: runner.os != 'Windows'

      - name: Build with Maven Wrapper (Windows)
        run: .\mvnw.cmd -V -B package
        if: runner.os == 'Windows'

      - name: Package Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl3-demos ${{ runner.os }} native image with SubstrateVM Java ${{ matrix.java-version }}
          path: target/lwjgl3-demos

      - name: Package Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl3-demos ${{ runner.os }} native image with SubstrateVM Java ${{ matrix.java-version }}
          path: target/lwjgl3-demos.exe

